ITC_AIR_FCR_SNOWPLOW = true;
ITC_AIR_FCR_DIR = [0,-5]; //current radar direction(az, el)
ITC_AIR_FCR_RNG = 5000; //distance at which to scan
ITC_AIR_FCR_SCANAZ = 0; //current scan azimuth
ITC_AIR_FCR_SCANXDIR = 1; //current horizontal scanning direction
ITC_AIR_FCR_SCANRNG = 30; //current scan range
ITC_AIR_FCR_TRAVLIM = 60; //traverse limit of radar, degrees from center
ITC_AIR_FCR_TRAVSPD = 24; //degrees per second
ITC_AIR_FCR_LASTFRAME = time;
ITC_AIR_FCR_TRACKING = [];
ITC_AIR_FCR_CURSOR_DIR = [0, 2500];
ITC_AIR_FCR_CURSOR_TRACKING = false;
ITC_AIR_FCR_CURSOR_TRACK = [0,0,0];
ITC_AIR_FCR_FREEZE = false;
ITC_AIR_FCR_FREEZE_POS = [0,0,0];
ITC_AIR_FCR_FREEZE_DIR = 0;
ITC_AIR_FCR_FREEZE_RNG = 0;
ITC_AIR_FCR_SCANPOS = [0,0,0];
